name: "scouting_app"
version: 1.0.0
services:
  server:
    restart: on-failure
#    container_name: "Nuxt"
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on:
      couchdb:
        condition: service_healthy
      couch-db-setup:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    links:
      - couchdb:couchdb
    environment:
      couchDBHostname: couchdb
    networks:
      - intercom_network
  devserver:
#    restart: on-failure

    build:
      context: .
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - path: .
          action: sync
          target: /usr/src/nuxt3-app
          ignore:
            - node_modules
            - bun.lockb
            - .npmrc
            - .gitignore
            - compose.yaml
            - Dockerfile
            - README.md
            - .nuxt
            - .output
            - .idea
            - .output
            - .data
            - .nuxt
            - .nitro
            - .cache
            - dist
        - path: testServer.js
          action: rebuild
          target: /usr/src/nuxt3-app/testServer.js
        - path: package.json
          action: rebuild
        - path: Dockerfile
          action: rebuild
    depends_on:
      couchdb:
        condition: service_healthy
      couch-db-setup:
        condition: service_completed_successfully
    ports:
      - "3010:3000"
    links:
      - couchdb:couchdb
    environment:
      couchDBHostname: couchdb
    networks:
      - intercom_network
#    profiles:
#      - "development"
  couchdb:
    restart: on-failure
    expose:
      - '5984'
    ports:
      - '5984:5984'
    #      - '4369:4369'
    #      - '9100:9100'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    image: 'couchdb:3'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - intercom_network
  couch-db-setup:
    restart: no
    depends_on:
      couchdb:
        condition: service_healthy
    build:
      context: .
      target: setup
      dockerfile: ./Dockerfile
    network_mode: service:couchdb
networks:
  intercom_network:
    name: intercom
    external: true
