services:
  server:
    build: .
    ports:
      - "3000:3000"
  couchdb:
    container_name: my-couchdb
    ports:
      - '5984:5984'
    #      - '4369:4369'
    #      - '9100:9100'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    image: 'couchdb:latest'
