name: "prod"
version: 1.0.0
services:
  server:
    env_file: .env
    restart: on-failure
    image: ghcr.io/durhamacademy/nuxtscoutingsystem:testing
    depends_on:
      couchdb:
        condition: service_healthy
      couch-db-setup:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    links:
      - couchdb:couchdb
    environment:
      - couchDBHostname=couchdb
      - COUCHDB_SERVER_USER=${SERVER_USERNAME}
      - COUCHDB_SERVER_PASSWORD=${SERVER_PASSWORD}
      - NITRO_SSL_CERT=${NITRO_SSL_CERT}
      - NITRO_SSL_KEY=${NITRO_SSL_KEY}
      - NUXT_TBA_KEY=${NUXT_TBA_KEY}
    networks:
      - intercom_network
  couchdb:
    env_file: .env
    restart: on-failure
    expose:
      - '5984'
      - '6984'
    environment:
      - COUCHDB_USER=${SERVER_USERNAME}
      - COUCHDB_PASSWORD=${SERVER_PASSWORD}
    ports:
      - '5984:5984'
      - '6984:6984'
    image: 'couchdb:3'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - intercom_network
    volumes:
      - couchDB:/opt/couchdb/data
      - ./couchdb_etc/local.d:/opt/couchdb/etc/local.d
      - ./couchdb_etc/fullchain1.pem:/opt/couchdb/etc/fullchain1.pem
      - ./couchdb_etc/privkey1.pem:/opt/couchdb/etc/privkey1.pem
  couch-db-setup:
    env_file: .env
    restart: on-failure
    depends_on:
      couchdb:
        condition: service_healthy
    build:
      target: setup
      dockerfile_inline: |
        FROM curlimages/curl:8.6.0 AS setup
        CMD curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_users; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_replicator; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_global_changes; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_node/nonode@nohost/_config/chttpd/enable_cors -d '"true"'; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_node/nonode@nohost/_config/cors/origins -d '"*"'; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_node/nonode@nohost/_config/cors/credentials -d '"true"'; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_node/nonode@nohost/_config/cors/methods -d '"GET, PUT, POST, HEAD, DELETE"'; \
            curl -s -X PUT http://${SERVER_USERNAME}:${SERVER_PASSWORD}@couchdb:5984/_node/nonode@nohost/_config/cors/headers -d '"accept, authorization, content-type, origin, referer, x-csrf-token"'
    network_mode: service:couchdb
networks:
  intercom_network:
    name: intercom
    external: false
volumes:
  couchDB:
    driver: local
    name: CouchDB_Volume
