on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d testserver
          docker-compose exec -T testserver npm run test run
          docker-compose down
        #idk what -T does but [this](https://stackoverflow.com/a/57565119/14994086) so thread told me to